

export const HANDLE_TODO_INPUT_ON_SUBMIT = 'HANDLE_TODO_INPUT_ON_SUBMIT';

export const HANDLE_TODO_INPUT_ONCHANGE = 'HANDLE_TODO_INPUT_ONCHANGE';

export const HANDLE_TODO_INPUT_REMOVE_ALL = 'HANDLE_TODO_INPUT_REMOVE_ALL';

export const HANDLE_REMOVE_TODO_OUTPUT_TEXT = 'HANDLE_REMOVE_TODO_OUTPUT_TEXT';

export const HANDLE_EDIT_TODO_OUTPUT_TEXT = 'HANDLE_EDIT_TODO_OUTPUT_TEXT';